import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./components/footer";
export const metadata = {
  title: "Dev-Maza",
  description: "Generated by Mazaharul isalm",
  icons:{
    icon:['/favicon.ico']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
<link rel="icon" href="/favicon.ico" sizes="any" />
<link
  rel="icon"
  href="/icon?<generated>"
  type="image/<generated>"
  sizes="<generated>"
/>

</head>
      <body className={`${inter.className} bg-[#111620]`} >

      <Header/>
  
    {children}
    <Footer/>
        </body>
    </html>
  );
}
